### ISSUE TITLE
Raspberry pi Initialization Issue

### ISSUE THREAD

**Issue by jalexcole** [CreedVI/Raylib-J#26]
**Describe the bug**
The bug is an aborted window when attempting to run the windowed examples on a raspberry pi. 

**To Reproduce**
Running an example

**Expected behavior**

pi@raspberrypi:~/Raylib-J $ /home/pi/Raylib-J ; /usr/bin/env /usr/lib/jvm/java-11-openjdk-armhf/bin/java -Dfile.encoding=UTF-8 @/tmp/cp_5j0gzvv0qwo1bkbr1c5zbcxph.argfile com.raylib.examples.shapes.BouncingBall 
INFO: Initializing raylib 3.7
WARNING: GLFW: Error: 65543 Description: -1240720732
WARNING: GLFW: Failed to initialize Window
INFO: TIMER: Target time per frame: 16.666666666666668 milliseconds
FATAL ERROR in native method: Thread[main,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
        at org.lwjgl.opengl.GL20C.glDisableVertexAttribArray(Native Method)
        at org.lwjgl.opengl.GL20.glDisableVertexAttribArray(GL20.java:1971)
        at com.raylib.rlgl.RLGL.UnloadRenderBatch(RLGL.java:1471)
        at com.raylib.rlgl.RLGL.rlglClose(RLGL.java:991)
        at com.raylib.core.Core.CloseWindow(Core.java:164)
        at com.raylib.core.Core.WindowShouldClose(Core.java:195)
        at com.raylib.examples.shapes.BouncingBall.main(BouncingBall.java:46)
Aborted

**Additional context**
Ran through gradle with the raspberry pi lwjgl dependencies.

**Comment by CreedVI** [comment]
The Gradle fork is currently maintained [here](https://github.com/jalexcole/Raylib-J)

However, from the GLFW error given it would appear the issue is your pi does not support the OpenGL version the system is trying to run. I do not own a Raspberry Pi to test or troubleshoot this issue on my own at this time.

**Comment by jalexcole** [comment]
Would you be willing to enable software fall back in the glfw window hint? That may be the best solution for now.
