### ISSUE TITLE
No context is current or a function that is not available in the current context was called. The JVM will abort execution.

### ISSUE THREAD

**Issue by ghost** [CreedVI/Raylib-J#28]
**Describe the bug**
```
$ ./gradlew run

> Task :run FAILED
INFO: Initializing raylib 4.0
WARNING: GLFW: Error: 65543 Description: 36103808
WARNING: GLFW: Failed to initialize Window
INFO: TIMER: Target time per frame: 16.666666666666668 milliseconds
FATAL ERROR in native method: Thread[main,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
        at org.lwjgl.opengl.GL20C.glDisableVertexAttribArray(Native Method)
        at org.lwjgl.opengl.GL20.glDisableVertexAttribArray(GL20.java:1948)
        at com.raylib.java.rlgl.RLGL.UnloadRenderBatch(RLGL.java:1527)
        at com.raylib.java.rlgl.RLGL.rlglClose(RLGL.java:1037)
        at com.raylib.java.core.rCore.CloseWindow(rCore.java:202)
        at com.raylib.java.core.rCore.WindowShouldClose(rCore.java:233)
        at com.raylib.java.Main.main(Main.java:33)

FAILURE: Build failed with an exception.
```

**To Reproduce**
1. `git clone https://github.com/AKDev21/temporary-repository.git`
2. `cd temporary-repository`
3. `gradlew run`

**Expected behavior**
core-window example

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version: 7 64 bit

**Comment by mateoox600** [comment]
I have no clue why but i did the step you told to do to reproduce the error but for me it work

**Comment by CreedVI** [comment]
What verson of OpenGL are you running? From what I can tell this appears to be an version specific issue.

**Comment by AKDev21** [comment]
`OpengL Version: 3.1.0 - Build 9.17.10.4229`

**Comment by CreedVI** [comment]
I believe the issue is that in OpenGL 3.0 `glbegin()` is depreciated and errors when called. Can you try manually setting your OpenGL version to 3.3 at line 953 in `RLGL.java` and try to run the example?
