### ISSUE TITLE
Special characters in DrawText make the program crash

### ISSUE THREAD

**Issue by mateoox600** [CreedVI/Raylib-J#30]
**Describe the bug**
Special characters in DrawText make the program crash

**To Reproduce**
[See linked code](https://github.com/CreedVI/Raylib-J/files/7800001/Terminaly.zip), launch it with connected raylib-j.jar and try to press any special characters like ç

**Expected behavior**
being able to draw special characters or to notify with a ? if it can't be rendered.

**Comment by CreedVI** [comment]
Resolved with commit 16d7f5d
