### ISSUE TITLE
rCore IsKeyDown is static - why?

### ISSUE THREAD

**Issue by nimbl0** [CreedVI/Raylib-J#31]
So toyday I tried to use the IsKeyDown method but it won't let me use it - why? Because it seems like I can't access it. Why is it the only static method of the four IsKeyXXX methods?

**Comment by CreedVI** [comment]
`IsKeyDown()` is currently static due to another module requiring the method. It's on my roadmap to resolve the static methods, but until then you can access it statically via `rCore.IsKeyDown()`
