### ISSUE TITLE
Missing import when trying to build raylib-j

### ISSUE THREAD

**Issue by mateoox600** [CreedVI/Raylib-J#33]
**Describe the bug**
When trying to build raylib-j, the import "com.sun.xml.internal.messaging.saaj.util.ByteInputStream"
 at the 5th line of rAudio, gives an error that the package does not exist.

**To Reproduce**
1. Clone Raylib-J.
2. Try to build it (if it fails for another reason try to create your own bulding artifact on intellij).
3. *See package does not exist error*

**Desktop:**
 - OS: Windows 10
 - Java: 17.0.1
 - Intellij-IDEA: 2021.3.3

**Additional context**
Maybe it's caused by some java weird thing but i can't find anything to resolve that issue

**Full erorr**:
```
C:\Users\MATHYS\Documents\Dev\Java\Raylib-J\src\com\raylib\java\raudio\rAudio.java:5:48
java: package com.sun.xml.internal.messaging.saaj.util does not exist
```

**Comment by CreedVI** [comment]
Swapped to using `ByteArrayInputStream`
