### ISSUE TITLE
Could not initialize class org.lwjgl.system.Library on macos

### ISSUE THREAD

**Issue by elias94** [CreedVI/Raylib-J#34]
Failed to load `lwjgl` on macos. This is the error reported when calling `InitWindow`.

```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.system.Library
```

I'm on macOS 12.4 with M1 chip. 

I'm loading the library using Clojure 1.11.1, and the creation of the Raylib `rCore` object happens correctly (`com.raylib.java.Raylib`). I notices that inside `natives` most of the `lwjgl` jar are for linux/windows. Is macos missing there?

Thanks for your job with the library 👍

**Comment by elias94** [comment]
Added packages into #35. Not sure how to the build process work to generate `Raylib-J.jar`

**Comment by CreedVI** [comment]
Thanks for flagging this issue and adding the packages! I'll close this when I merge #35. 

To build using Intellij Idea: see [this article](https://www.jetbrains.com/help/idea/working-with-artifacts.html)
Make sure you extract the contents of the `natives` directory to the jar

**Comment by elias94** [comment]
Never used Intellij Idea before and not sure how to work with jar files. Can you make a new build with the natives files? I took the old jar from https://github.com/CreedVI/Raylib-J-Examples since wasn't included in this repo
