### ISSUE TITLE
Texture images are not loading

### ISSUE THREAD

**Issue by BlueFalcon234** [CreedVI/Raylib-J#39]
**Describe the bug**
I am using the texture and rTexture module, and I am loading a texture2D, then I am trying to draw that texture to the screen but I get a error of 
“FILElO: File name provided is not valid resources/raylib-j_logo.png”

Even though the file path is actually valid.

I also even used the Raylib-j texture example from the example repository to draw to raylib-j logo, but still getting the same error.

The jar file I am using is Raylib-j_0.4.jar, and the IDE I am using is IntelliJ IDEA Community 2023.1.1, on Windows 10.

**Comment by CreedVI** [comment]
Is your IntelliJ project configured to include the assets in your build output? 

https://www.jetbrains.com/help/idea/add-items-to-project.html#import-image-to-project

**Comment by BlueFalcon234** [comment]
Oh I see thank you so much! I just tried that out it worked. Just was a little unfamiliar with IntelliJ, thanks for that help!

-blue
