### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by kles4enko** [CreedVI/Raylib-J#44]
**Is your feature request related to a problem? Please describe.**
I would like to easily kick-off new project with standart tools like Maven or Gradle, with a propper dependency management. It also will allow smooth compiling of the final game on CI for different platforms. 

**Describe the solution you'd like**
I see that it can be ticky part, cause the project itserlf doesn't use propper build management tool. So, I would start with modularity and moving this porject itself to Maven or Gradle.

**Describe alternatives you've considered**
Alternatively, just publish to maven existing build outputs for different platfroms, i.t. Linux, MacOS, Windows.

**Additional context**
-

**Comment by CreedVI** [comment]
I agree with a lot of the sentiment in your post, but refactoring the project to use a new build system is an immense undertaking that I simply do not have time for at the moment. 

I currently use the build system built into InelliJ to build the project, but have been planning to swap over to Maven or Gradle in the future; I've no experience with either, so I'm open to suggestion, or if you would like to create a fork for your preferred system and issue a pull request - that is always an option.
